// AUTO-GENERATED FILE. DO NOT EDIT.
// Generated by GenerateIcon.swift during build.
import Cocoa

struct AppPersonality {
    static let color = NSColor(calibratedRed: 1.0, green: 0.8607969880104065, blue: 0.0, alpha: 1.0)
}