// AUTO-GENERATED FILE. DO NOT EDIT.
// Generated by GenerateIcon.swift during build.
import Cocoa

struct AppPersonality {
    static let color = NSColor(calibratedRed: 0.23529411764705882, green: 0.8274509803921568, blue: 0.996078431372549, alpha: 1.0)
}