// AUTO-GENERATED FILE. DO NOT EDIT.
// Generated by GenerateIcon.swift during build.
import Cocoa

struct AppPersonality {
    static let color = NSColor(calibratedRed: 1.0, green: 0.3005654513835907, blue: 0.2565172612667084, alpha: 1.0)
}