import Cocoa

let iconSize = CGSize(width: 1024, height: 1024)
let image = NSImage(size: iconSize)

image.lockFocus()

guard let ctx = NSGraphicsContext.current?.cgContext else {
    print("Failed to get graphics context")
    exit(1)
}

// Draw the squircle background
let bgRect = NSRect(origin: .zero, size: iconSize)
let bgPath = NSBezierPath(roundedRect: bgRect, xRadius: 224, yRadius: 224)

// Gradient from dark slate to deep purple/black (like a stealth night-vision camera body)
let colors = [NSColor(calibratedRed: 0.15, green: 0.15, blue: 0.18, alpha: 1.0).cgColor,
              NSColor(calibratedRed: 0.05, green: 0.05, blue: 0.08, alpha: 1.0).cgColor] as CFArray
let colorSpace = CGColorSpaceCreateDeviceRGB()
let gradient = CGGradient(colorsSpace: colorSpace, colors: colors, locations: [0.0, 1.0])!
ctx.drawLinearGradient(gradient, start: CGPoint(x: 0, y: iconSize.height), end: CGPoint(x: 0, y: 0), options: [])

bgPath.addClip()

// Configure the "eye.fill" symbol
var activeTintColor: NSColor = .systemBlue
let symbolConfig = NSImage.SymbolConfiguration(pointSize: 600, weight: .semibold)
if let symbol = NSImage(systemSymbolName: "eye.fill", accessibilityDescription: nil)?.withSymbolConfiguration(symbolConfig) {
    let curatedColors: [NSColor] = [
        .systemBlue, .systemCyan, .systemPurple, .systemOrange,
        .systemPink, .systemIndigo, .systemTeal, .systemMint,
        .systemGreen, .systemYellow, .systemRed,
        NSColor(calibratedRed: 0.0, green: 0.9, blue: 0.7, alpha: 1.0), // Neon Turquoise
        NSColor(calibratedRed: 0.9, green: 0.1, blue: 0.5, alpha: 1.0), // Electric Pink
        NSColor(calibratedRed: 0.5, green: 0.0, blue: 1.0, alpha: 1.0), // Deep Violet
        NSColor(calibratedRed: 1.0, green: 0.6, blue: 0.0, alpha: 1.0), // Bright Mango
        NSColor(calibratedRed: 0.1, green: 0.8, blue: 0.3, alpha: 1.0)  // Toxic Green
    ]
    activeTintColor = curatedColors.randomElement() ?? .systemBlue
    let tintedSymbol = NSImage(size: symbol.size)
    tintedSymbol.lockFocus()
    activeTintColor.set()
    let rect = NSRect(origin: .zero, size: symbol.size)
    rect.fill()
    symbol.draw(in: rect, from: .zero, operation: .destinationIn, fraction: 1.0)
    tintedSymbol.unlockFocus()
    
    // Center logic
    let xOffset = (iconSize.width - tintedSymbol.size.width) / 2.0
    let yOffset = (iconSize.height - tintedSymbol.size.height) / 2.0
    let symbolRect = NSRect(x: xOffset, y: yOffset, width: tintedSymbol.size.width, height: tintedSymbol.size.height)
    
    // Add subtle shadow for depth
    let shadow = NSShadow()
    shadow.shadowColor = NSColor.black.withAlphaComponent(0.6)
    shadow.shadowOffset = NSSize(width: 0, height: -10)
    shadow.shadowBlurRadius = 15
    shadow.set()
    
    tintedSymbol.draw(in: symbolRect)
} else {
    print("Could not find eye.fill symbol")
    exit(1)
}

image.unlockFocus()

// Save to disk
guard let tiffData = image.tiffRepresentation,
      let bitmap = NSBitmapImageRep(data: tiffData),
      let pngData = bitmap.representation(using: .png, properties: [:]) else {
    print("Failed to create PNG representation")
    exit(1)
}

let fileURL = URL(fileURLWithPath: "../icon.png")
do {
    try pngData.write(to: fileURL)
    print("Successfully generated icon.png")
    
    // --- Generate Swift Source File with the identical color ---
    let rgbColor = activeTintColor.usingColorSpace(.deviceRGB) ?? activeTintColor
    let swiftCode = """
    // AUTO-GENERATED FILE. DO NOT EDIT.
    // Generated by GenerateIcon.swift during build.
    import Cocoa

    struct AppPersonality {
        static let color = NSColor(calibratedRed: \(rgbColor.redComponent), green: \(rgbColor.greenComponent), blue: \(rgbColor.blueComponent), alpha: \(rgbColor.alphaComponent))
    }
    """
    
    let swiftFileURL = URL(fileURLWithPath: "Sources/GeneratedColor.swift")
    try swiftCode.write(to: swiftFileURL, atomically: true, encoding: String.Encoding.utf8)
    print("Successfully generated Sources/GeneratedColor.swift")

} catch {
    print("Failed to write files: \(error)")
    exit(1)
}
